name: zypher-os
description: "The Ultimate Creator's Workstation"
base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: latest

modules:
# BLOCK A: Setup Repositories (The Plumbing)
  - type: script
    scripts:
      # 1. Import Security Keys explicitly
      - rpm --import https://dl.google.com/linux/linux_signing_key.pub
      - rpm --import https://packages.microsoft.com/keys/microsoft.asc
      
      # 2. Download Official Google Chrome Repo File
      - curl -Lo /etc/yum.repos.d/google-chrome.repo https://dl.google.com/linux/chrome/rpm/stable/x86_64/google-chrome.repo
      
      # 3. Create VS Code Repo File (Using simple echo)
      - sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

  # BLOCK B: Install Packages (The Action)
  - type: rpm-ostree
    # We stripped out Ghostty for this run to ISOLATE the Chrome issue. 
    # If this passes, we add Ghostty back next.
    remove:
      - firefox
      - firefox-langpacks
    install:
      - google-chrome-stable
      - code
      - plymouth-theme-spinner
      - zsh
      - fastfetch
      
  # 3. COPY YOUR CUSTOM FILES
  - type: files
    files:
      - source: files/usr
        destination: /usr
      - source: files/etc/os-release
        destination: /usr/lib/os-release

  # 4. FINAL BRANDING SCRIPTS
  - type: script
    scripts:
      - /usr/bin/plymouth-set-default-theme -R spinner
