name: zypher-os
description: "The Ultimate Creator's Workstation"
base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: latest

modules:
  # 1. SYSTEM PACKAGES (VS Code & Ghostty)
  - type: rpm-ostree
    # Import keys so the build trusts Microsoft & Ghostty
    keys:
      - https://packages.microsoft.com/keys/microsoft.asc
      - https://download.copr.fedorainfracloud.org/results/pgdev/ghostty/pubkey.gpg

    # Add Ghostty Repo (VS Code is handled by the file we just made)
    repos:
      - https://copr.fedorainfracloud.org/coprs/pgdev/ghostty/repo/fedora-%OS_VERSION%/pgdev-ghostty-fedora-%OS_VERSION%.repo

    # Cleanup
    remove:
      - firefox
      - firefox-langpacks

    # Install System Tools (No Chrome here!)
    install:
      - code
      - ghostty
      - plymouth-theme-spinner
      - zsh
      - fastfetch

  # 2. FLATPAKS (Chrome goes here)
  - type: default-flatpaks
    notify: true
    system:
      # Browsers
      - repo: flathub
        name: com.google.Chrome
      # Creative Tools
      - repo: flathub
        name: com.obsproject.Studio
      - repo: flathub
        name: org.gimp.GIMP
      # System
      - repo: flathub
        name: com.github.tchx84.Flatseal
