name: zypher-os
description: "The Ultimate Creator's Workstation"
base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: latest

modules:
  # 1. REPO SETUP (Address Book First)
  - type: files
    files:
      - source: etc/yum.repos.d
        destination: /etc/yum.repos.d

  # 2. SYSTEM PACKAGES
  - type: rpm-ostree
    # Import Keys
    keys:
      - https://packages.microsoft.com/keys/microsoft.asc
    
    # Install Packages
    install:
      - code
      - zsh
      - fastfetch
      - plymouth-theme-spinner  <-- ADD THIS LINE

  # 3. FLATPAKS
  - type: default-flatpaks
    configurations:
      - install:
          - com.google.Chrome
          - com.github.tchx84.Flatseal

  # 4. BRANDING & ASSETS (Name Change Last)
  - type: files
    files:
      - source: etc/os-release
        destination: /etc/os-release
      # Uncomment this once the build passes and you confirm 'usr' is correct
      - source: usr
        destination: /usr

  # 5. FINAL CLEANUP
  - type: script
    scripts:
      - scripts/plymouth.sh  # Runs your custom script file
