name: zypher-os
description: "The Ultimate Creator's Workstation"
base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: latest

modules:
# 1. ADD REPOS (Manual File Creation)
  - type: script
    scripts:
      - |
        cat <<EOF > /etc/yum.repos.d/google-chrome.repo
        [google-chrome]
        name=google-chrome
        baseurl=https://dl.google.com/linux/chrome/rpm/stable/x86_64
        enabled=1
        gpgcheck=1
        gpgkey=https://dl.google.com/linux/linux_signing_key.pub
        EOF

  # 2. SYSTEM PACKAGES
  - type: rpm-ostree
    remove:
      - firefox
      - firefox-langpacks
    install:
      - google-chrome-stable
      - plymouth-theme-spinner
      - ghostty
      - code
      - zsh
      - fastfetch

  # 3. COPY YOUR CUSTOM FILES
  - type: files
    files:
      - source: files/usr
        destination: /usr
      - source: files/etc/os-release
        destination: /usr/lib/os-release

  # 4. FINAL BRANDING SCRIPTS
  - type: script
    scripts:
      - /usr/bin/plymouth-set-default-theme -R spinner
