name: zypher-os
description: "The Ultimate Creator's Workstation"
base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: latest

modules:
  # 1. FILES (Copies your fixed folder structure)
  - type: files
    files:
      - source: usr
        destination: /usr
      - source: etc
        destination: /etc

  # 2. SYSTEM PACKAGES (Safe Mode)
  - type: rpm-ostree
    # Import Keys
    keys:
      - https://packages.microsoft.com/keys/microsoft.asc
    
    # Install ONLY VS Code first to prove it works
    remove:
      - firefox
      - firefox-langpacks
    install:
      - code
      - zsh
      - fastfetch

  # 3. FLATPAKS
  - type: default-flatpaks
    configurations:
      - install:
          - com.google.Chrome
          - com.github.tchx84.Flatseal