name: zypher-os
description: "The Ultimate Creator's Workstation"
base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: latest

modules:
# 2. SYSTEM PACKAGES (The Native Way)
  - type: rpm-ostree
    # A. Import Security Keys First
    keys:
      - https://dl.google.com/linux/linux_signing_key.pub
      - https://packages.microsoft.com/keys/microsoft.asc

    # B. Add Repositories (For Ghostty)
    repos:
      - https://copr.fedorainfracloud.org/coprs/pgdev/ghostty/repo/fedora-%OS_VERSION%/pgdev-ghostty-fedora-%OS_VERSION%.repo

    # C. Remove Firefox
    remove:
      - firefox
      - firefox-langpacks

    # D. Install Packages (Direct RPM URLs + Repo Packages)
    install:
      # Google Chrome (Direct Install)
      - https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
      # VS Code (Direct Install)
      - https://packages.microsoft.com/yumrepos/vscode/code-1.96.2-1734607870.el8.x86_64.rpm
      # System Tools
      - plymouth-theme-spinner
      - ghostty
      - zsh
      - fastfetch

  # 3. COPY YOUR CUSTOM FILES
  - type: files
    files:
      - source: files/usr
        destination: /usr
      - source: files/etc/os-release
        destination: /usr/lib/os-release

  # 4. FINAL BRANDING SCRIPTS
  - type: script
    scripts:
      - /usr/bin/plymouth-set-default-theme -R spinner
