name: zypher-os
description: "The Ultimate Creator's Workstation"
base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: latest

modules:
  # 1. FILES (Copy Repos & Branding FIRST)
  # This puts 'vscode.repo' in the right place so the next step can find it.
  - type: files
    files:
      - source: files/usr
        destination: /usr
      - source: files/etc
        destination: /etc

  # 2. SYSTEM PACKAGES
  - type: rpm-ostree
    # Import keys
    keys:
      - https://packages.microsoft.com/keys/microsoft.asc
      - https://download.copr.fedorainfracloud.org/results/pgdev/ghostty/pubkey.gpg

    # Add Ghostty Repo
    repos:
      - https://copr.fedorainfracloud.org/coprs/pgdev/ghostty/repo/fedora-%OS_VERSION%/pgdev-ghostty-fedora-%OS_VERSION%.repo

    # Cleanup
    remove:
      - firefox
      - firefox-langpacks

    # Install RPMs (Now it will find 'code'!)
    install:
      - code
      - ghostty
      - plymouth-theme-spinner
      - zsh
      - fastfetch

  # 3. FLATPAKS (Correct v2 Syntax)
  - type: default-flatpaks
    configurations:
      - install:
          - com.google.Chrome
          - com.obsproject.Studio
          - org.gimp.GIMP
          - com.github.tchx84.Flatseal

  # 4. FINAL CLEANUP
  - type: script
    scripts:
      - /usr/bin/plymouth-set-default-theme -R spinner
