name: zypher-os
description: "The Ultimate Creator's Workstation"
base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: 41

modules:
  # 1. ADD REPOS (Google Chrome)
  - type: script
    scripts:
      - /usr/bin/dnf5 config-manager --add-repo https://dl.google.com/linux/chrome/rpm/stable/x86_64

  # 2. SYSTEM PACKAGES
  - type: rpm-ostree
    remove:
      - firefox
      - firefox-langpacks
    install:
      - google-chrome-stable
      - plymouth-theme-spinner
      - ghostty
      - code
      - zsh
      - fastfetch

  # 3. COPY YOUR CUSTOM FILES
  - type: files
    files:
      - source: files/usr
        destination: /usr
      - source: files/etc/os-release
        destination: /usr/lib/os-release

  # 4. FINAL BRANDING SCRIPTS
  - type: script
    scripts:
      - /usr/bin/plymouth-set-default-theme -R spinner
